### ISSUE TITLE
TimeZone delle date RPT/RT 

### ISSUE THREAD

**Issue by ga2arch** [italia/pagopa-doc-formatoXML#3]
Attualmente non mi sembra sia specificato il timezone da usare nelle date da inserire all'interno di RPT/RT e xml di rendicontazione, cosa che invece viene fatta nel documento che specifica il formato del giornale degli eventi.

Parlando con Agid so che va usato Europe/Rome altrimenti potrebbe "mandare in confusione" (virgoletto dato che così mi è stato comunicato via mail) gli enti creditori. 

Propongo di aggiungerlo nella documentazione così da evitare incomprensioni.

**Comment by giupal** [comment]
Perfetto, grazie mille!

**Comment by ruphy** [comment]
@giupal il problema è stato risolto con un commit?

**Comment by giupal** [comment]
Si, è stato risolto con una commit.
