### ISSUE TITLE
Errore Test Case WS-1.1.8

### ISSUE THREAD

**Issue by ga2arch** [italia/pagopa-doc-formatoXML#4]
>> Premetto che non so se questo sia il posto giusto dove fare questa segnalazione dato che riguarda il verbale di abilitazione all'esercizio e non la doc in sè, nel caso, indicatemi dove aprire la issue (ho già provveduto a segnalarlo via mail)

Il test case in questione, presente nel verbale di approvazione all'esercizio:
`ProceduraAbilitazioneEsercizioPSP_Bollo_v_2_1` è errato in quanto:

![testcase](https://user-images.githubusercontent.com/14008/33658866-7b830dca-da7e-11e7-93ab-988fd36b239a.png)

In seguito ad un ACK negativo il PSP deve rispondere `OK` di presa consegna dell'ACK negativo e non rispondere con un errore.

**Comment by giuseppevirgone** [comment]
Fai pervenire questa richiesta a attivazionepagopa@agid.gov.it

**Comment by ga2arch** [comment]
Già inviata giorni fa, segnalavo ulteriormente per scrupolo, direi che si può chiudere
