### ISSUE TITLE
Formato date RPT/RT 

### ISSUE THREAD

**Issue by ga2arch** [italia/pagopa-doc-formatoXML#5]
Nel file PagInf_RPT_RT_6.2.0.xsd le date vengono specificate con: 

```
	<xsd:simpleType name="stISODate">
		<xsd:restriction base="xsd:date"/>
	</xsd:simpleType>

	<xsd:simpleType name="stISODateTime">
		<xsd:restriction base="xsd:dateTime"/>
	</xsd:simpleType>
```

nelle specifiche `Lineeguida_All.B_Specifiche_Attuative_Nodo.pdf` molto spesso viene specificato che le date devono essere in formato ISO 8601 con una indicazione extra sulla formattazione da impostare (es. `[YYYY]-[MM]-[DD]`, `[YYYY]-[MM]-[DD]T[hh]:[mm]:[ss]`). 

Dato che alcuni enti creditori rifiutato le RT se questa data non è formattata correttamente 
secondo le linee guida ma è comunque in un formato ISO 8601 valido (esempio reale ci hanno rifiutato delle RT poiché la data del versamento era nel formato `[YYYY]-[MM]-[DD]`**Z** che secondo specifiche xsd:date è un formato valido), propongo di forzare la formattazione delle date nel xsd stesso utilizzando il campo `<xs:pattern value="">`.

esempio per il caso di prima: 

```
<xsd:simpleType name="stISODate">
    <xs:restriction base="xs:date">
        <xs:pattern value="[^:Z]*"/>
    </xs:restriction>
</xsd:simpleType>
```

**Comment by giupal** [comment]
Grazie @ga2arch
