### ISSUE TITLE
Schemi XSD aggiornati al documento dei formati XML 

### ISSUE THREAD

**Issue by brunato** [italia/pagopa-doc-formatoXML#6]
Cercavo i file XSD per i formati XML contenuti nel documento, allo scopo di poter validare i dati.
Ho trovato degli schemi sul sito AGID al seguente link:

  http://www.agid.gov.it/sites/default/files/linee_guida/appendice_3_allegato_b_6_0.zip

ma vedendo le date dei file volevo chiedere se vi sono versioni nuove degli schemi e dove trovarli.
In ogni caso quando saranno disponibili perché non aggiungerli al repo o almeno inserire un link nel documento?

Grazie

Davide Brunato

**Comment by giupal** [comment]
Gentile brunato,
grazie per la tua segnalazione.

Al momento ti consigliamo di riferimento agli schemi del sito AGID.  
A breve usciranno sul sito AGID e poi su developers le integrazioni che prevedono l’avvisatura digitale.

**Comment by brunato** [comment]
Ok, grazie
